[build-system]
requires = ["poetry-core>=2.1.2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "wealth"
version = "0.1.0"
description = ""
authors = ["Alan Szmyt <szmyty@gmail.com>"]
license = "MIT"
readme = "README.md"
# packages = [{ include = "cli" }]

[tool.poetry.dependencies]
python = "^3.12"

# [tool.poetry.scripts]
# cli = "cli.cli:cli"
pydantic = "^2.11.5"
pandas = "^2.2.3"
faker = "^37.3.0"
