---
PRESET: linters-without-autofix

ENABLE_LINTERS:
  - TYPESCRIPT_ESLINT
  - JAVASCRIPT_ESLINT
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - DOCKERFILE_HADOLINT
  - SHELL_SHFMT
  - SPELL_CSPELL

AUTO_FIX: true
GITHUB_WORKSPACE: .
DEFAULT_WORKSPACE: .
REPORT_OUTPUT_FOLDER: .mega-linter-reports
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false

FILTER_REGEX_EXCLUDE: "node_modules|dist|build|\\.changeset|\\.devcontainer"
