version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - db
      - keycloak

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${UI_PORT:-5173}:5173"

  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_DB: ${API_DB_NAME:-wealth}
      POSTGRES_USER: ${API_DB_USER:-wealth}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD:-wealthpass}
    ports:
      - "${API_DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloakpass}
    ports:
      - "${KEYCLOAK_DB_PORT:-5433}:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloakpass}
    command: start-dev
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    depends_on:
      - keycloak-db

volumes:
  db-data:
  keycloak-db-data:
