---
services:
  api:
    command: uvicorn services.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.staging

  ui:
    command: pnpm preview --host --port 5173
    env_file:
      - .env.staging

  apache:
    env_file:
      - .env.staging

  keycloak:
    env_file:
      - .env.staging
