version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${UI_PORT:-5173}:5173"
