name: MegaLinter

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  mega-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Run MegaLinter
        run: npx mega-linter-runner --path .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
